[SystemSettings]
; --- Qualidade Base Máxima ---
r.AmbientOcclusion.Method=1
r.AOQuality=2
r.AOSampleSet=0
r.AOSpecularOcclusionMode=1
r.Atmosphere=1
r.BloomQuality=5
r.ContactShadows=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=1
r.DefaultFeature.LightUnits=2
r.DefaultFeature.MotionBlur=0
r.DetailMode=2
r.DFFullResolution=1
r.DFShadowQuality=3
r.ForceHighestMipOnUITextures=1
r.GBufferFormat=5
r.GTAO.NumAngles=16
r.LensFlareQuality=3
r.MaterialQualityLevel=3
r.MaxAnisotropy=16

; --- Melhorias Específicas para RX 6750 XT (Visual Extra) ---
r.ViewDistanceScale=5
r.StaticMeshLODDistanceScale=0.1
r.Shadow.DistanceScale=4
r.Tonemapper.Sharpen=1
r.SceneColorFringeQuality=0
r.PostProcessAAQuality=6